### ISSUE TITLE
Updated Copasi output:  637

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/temp-biomodels#109]
Copasi now generates different output for biomodels 638, which makes one of our replacements out of sync.  Our current replacement rule is:

```
BIOMD0000000637:
  - filename: 'Bush2016-Simplified-Carrousel-model-of-GPCR.sedml'
    type: replace_text
    old: >
      <dataSet id="ds_4_task3" dataReference="_1_task3"/>
    new: >
      <dataSet id="ds_4_task3" label="Gbg" dataReference="Gbg_1_task3"/>
```
But now the dataSets are:

```
      <listOfDataSets>
        <dataSet id="ds_1_task3" label="k_off_R_G" dataReference="k_off_R_G_1_task3"/>
        <dataSet id="ds_2_task3" label="Rtot" dataReference="Rtot_1_task3"/>
        <dataSet id="ds_3_task3" label="L" dataReference="L_1_task3"/>
        <dataSet id="ds_4_task3" label="tot_LR" dataReference="tot_LR_1_task3"/>
      </listOfDataSets>
```
The original final version of the SED-ML was:

```
      <listOfDataSets>
        <dataSet id="ds_1_task3" label="k_off_R_G" dataReference="k_off_R_G_1_task3"/>
        <dataSet id="ds_2_task3" label="Rtot" dataReference="Rtot_1_task3"/>
        <dataSet id="ds_3_task3" label="L" dataReference="L_1_task3"/>
        <dataSet id="ds_4_task3" label="Gbg" dataReference="Gbg_1_task3"/>
        <dataSet id="ds_5_task3" label="tot_LR" dataReference="tot_LR_1_task3"/>
      </listOfDataSets>
```
So, as far as I can tell, the original fix involved taking a broken dataSet, and replacing it with a new one that Copasi didn't originally put in that report.  In the latest version, Copasi doesn't put the broken dataSet in the report in the first place, and we thus can't replace it with a new one.  

@jonrkarr : do we want to insert Gbg into the report anyway?  It's currently in the figure but not the report.  (Also note that we now have a new report with *all* the data from task3, if that's the intent of the original change.)

New versions of SED-ML and SBML (without the new dataSet) attached.

[BIOMD0000000637_url.xml.txt](https://github.com/sys-bio/temp-biomodels/files/8063791/BIOMD0000000637_url.xml.txt)
[Bush2016-Simplified-Carrousel-model-of-GPCR.sedml.txt](https://github.com/sys-bio/temp-biomodels/files/8063792/Bush2016-Simplified-Carrousel-model-of-GPCR.sedml.txt)
